---
# tasks file for js
- name: Install nvm
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"

- name: Install node
  become: no
  ansible.builtin.shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    #creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
  loop:
    - node #"node" is an alias for the latest version

- name: Install npm
  become: no
  ansible.builtin.shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install-latest-npm
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
