---
# tasks file for roles/misc

- name: Platform check
  debug:
    msg:
      - OS family is {{ ansible_os_family }}
      - Package manager is {{ansible_pkg_mgr}}

- name: Install utils
  ansible.builtin.package:
    name:
      - ranger
      - tmux
    state: latest
  become: yes
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install utils
  ansible.builtin.apt:
    name:
      - ranger
      - tmux
    state: latest
  become: yes
  when: ansible_facts['os_family'] == "Debian" # Debian, Ubuntu
